theme: jekyll-theme-minimal
title: Stephanie Thompson | Sr. Full Stack Web Developer
logo: https://avatars1.githubusercontent.com/u/43892794?s=460&u=a346bc61b2075d389a7b2420002f2e290e33f5ea&v=4
description: https://www.linkedin.com/in/thompson-steph/  https://www.behance.net/stephrthompson 
