theme: jekyll-theme-minimal
title: Stephanie Thompson | Sr. Full Stack Web Developer
description: Welcome to my portfolio. Here you will find a collection of items that I worked on in my time at SNHU's Computer Science program along with a handful of freelance projects I have completed.
